
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_PAGE = 'SET_PAGE'
export const REQUEST_AUTH = 'REQUEST_AUTH'
export const RECEIVE_AUTH_SUCCESS = 'RECEIVE_AUTH_SUCCESS'
export const RECEIVE_AUTH_FAILURE = 'RECEIVE_AUTH_FAILURE'
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const REQUEST_ACCOUNT = 'REQUEST_ACCOUNT'
export const SET_ACCOUNT = 'SET_ACCOUNT'
